"""PT-TEMPO dynamics from a directly supplied cross-spectral-density tensor.

The input ``Js`` follows the Quantarhei mapping used in the original script:

    J[0, 0] = Js['J_ee_ee']
    J[1, 1] = Js['J_ff_ff']
    J[2, 2] = Js['J_ef_ef']
    J[0, 1] = Js['J_ee_ff']
    J[0, 2] = Js['J_ef_ee']
    J[1, 2] = Js['J_ef_ff']

The reverse entries are generated by Hermitian conjugation. If the supplied
cross spectra are real and symmetric, this is equivalent to copying them.
"""

import numpy as np
from scipy.interpolate import interp1d

import oqupy
from heom_qutip import cm1_to_rad_per_fs, kbt_cm1
import quantarhei as qr


def _spectral_density_matrix(Js, conversion_factor):
    """Return the six supplied spectra in OQuPy frequency units."""
    frequency_cm1 = np.asarray(Js["J_ee_ee"].x[1:], dtype=float)
    spectra_cm1 = np.vstack([
        np.pi * frequency_cm1**2 * np.asarray(
            Js["J_ee_ee"].y[1:]),
        np.pi * frequency_cm1**2 * np.asarray(
            Js["J_ff_ff"].y[1:]),
        np.pi * frequency_cm1**2 * np.asarray(
            Js["J_ef_ef"].y[1:]),
        np.pi * frequency_cm1**2 * np.asarray(
            Js["J_ee_ff"].y[1:]),
        np.pi * frequency_cm1**2 * np.asarray(
            Js["J_ef_ee"].y[1:]),
        np.pi * frequency_cm1**2 * np.asarray(
            Js["J_ef_ff"].y[1:]),
    ])
    # J_rad/fs(w_rad/fs) dw_rad/fs = J_cm1(w_cm1) dw_cm1 / pi.
    spectra_rad_fs = spectra_cm1 / (np.pi * conversion_factor)
    return frequency_cm1 * conversion_factor, spectra_rad_fs


def _make_custom_sd(frequency, values, temperature, cutoff,
                    epsrel=1.0e-6, subdiv_limit=64):
    """Build a piecewise-linear CustomSD without applying another cutoff."""
    frequency = np.asarray(frequency, dtype=float)
    values = np.asarray(values, dtype=complex).copy()
    if frequency[0] > 0.0:
        frequency = np.insert(frequency, 0, 0.0)
        values = np.insert(values, 0, 0.0)
    else:
        values[0] = 0.0
    interpolator = interp1d(
        frequency,
        values,
        kind="linear",
        bounds_error=False,
        fill_value=0.0,
    )
    return oqupy.CustomSD(
        j_function=interpolator,
        cutoff=cutoff,
        cutoff_type="hard",
        temperature=temperature,
        epsrel=epsrel,
        subdiv_limit=subdiv_limit,
        integration_points=frequency,
    )


def run_cross_correlated_pt_tempo(params, Js, ftime=None, dt=None,
                                  dkmax=None, epsrel=7.209e-12,
                                  correlation_epsrel=1.0e-6,
                                  backend_config=None):
    """Compute dynamics using the original, non-decomposed spectral tensor."""
    if ftime is None:
        ftime = params["ftime"]
    if dt is None:
        dt = params["dt"]

    conversion_factor = cm1_to_rad_per_fs(1.0)
    frequency, spectra = _spectral_density_matrix(Js, conversion_factor)
    temperature = conversion_factor * kbt_cm1(params["T"])
    cutoff = frequency[-1]

    # Original physical channel basis: ee, ff, and ef.
    operators = [
        np.diag([0.0, 1.0, 0.0]),
        np.diag([0.0, 0.0, 1.0]),
        np.array([[0.0, 0.0, 0.0],
                  [0.0, 0.0, 1.0],
                  [0.0, 1.0, 0.0]]),
    ]

    auto_ee, auto_ff, auto_ef, cross_ee_ff, cross_ef_ee, cross_ef_ff = spectra
    spectral_values = [
        [auto_ee, cross_ee_ff, cross_ef_ee],
        [np.conjugate(cross_ee_ff), auto_ff, cross_ef_ff],
        [np.conjugate(cross_ef_ee), np.conjugate(cross_ef_ff), auto_ef],
    ]
    correlation_matrix = [
        [_make_custom_sd(frequency, values, temperature, cutoff,
                  epsrel=correlation_epsrel)
         for values in row]
        for row in spectral_values
    ]
    bath = oqupy.Bath(operators, correlation_matrix,
                       name="direct cross-correlated vibronic bath")

    with qr.energy_units("1/cm"):
        molecule = qr.Molecule(elenergies=params["energies"])
        molecule.build()
        bare_hamiltonian = molecule.get_Hamiltonian().data

    hamiltonian = conversion_factor * bare_hamiltonian
    for channel, operator in enumerate(operators):
        mask = frequency > 1.0e-8
        reorganization = np.trapz(
            np.real(spectral_values[channel][channel][mask]) /
            frequency[mask], frequency[mask])
        hamiltonian += reorganization * (operator @ operator)
    system = oqupy.System(hamiltonian)

    excited_state = np.array([0.0, 0.0, 1.0], dtype=complex)
    initial_state = np.outer(excited_state, excited_state.conjugate())
    parameters = oqupy.TempoParameters(
        dt=dt,
        dkmax=dkmax,
        epsrel=epsrel,
    )
    process_tensor = oqupy.pt_tempo_compute(
        bath=bath,
        start_time=0.0,
        end_time=ftime,
        parameters=parameters,
        backend_config=backend_config,
    )
    dynamics = oqupy.compute_dynamics(
        system=system,
        process_tensor=process_tensor,
        initial_state=initial_state,
        start_time=0.0,
    )
    populations = np.real(
        np.diagonal(dynamics.states, axis1=1, axis2=2)).T
    return dynamics.times, populations
